networks:
  servermanager:
    name: servermanager
    external: true
  webservice:
    name: webservice-${HOSTNAME:-default}
    external: false
    ipam:
      driver: default
      config:
        - subnet: 172.${IP:-0}.0.0/16

services:
  webservice:
    build:
      dockerfile: ./docker/images/dockerfile.dev
    expose:
      - "8080"
    volumes:
      - ./app:/go/src/app
      # mount source for live reload
      - ./app/go-mod-cache:/go/pkg/mod
      - ./app/.air.toml:/go/src/app/.air.toml:ro
    networks:
      - servermanager
      - webservice
