networks:
  servermanager:
    name: servermanager
    external: true
  webservice:
    name: webservice-${HOSTNAME:-default}
    external: false
    ipam:
      driver: default
      config:
        - subnet: 172.${IP:-0}.0.0/16

services:
  webservice:
    build:
      dockerfile: ./docker/images/dockerfile.dev
    expose:
      - "8080"
    volumes:
      - ./app:/go/src/app
      # mount source for live reload
      - ./app/go-mod-cache:/go/pkg/mod
      - ./app/.air.toml:/go/src/app/.air.toml:ro
    networks:
      - servermanager
      - webservice

  db:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=todos_db
    volumes:
      - ./docker/mariadb/my.cnf:/etc/mysql/conf.d/my.cnf:ro
      - ./docker/mariadb/data:/var/lib/mysql
    networks:
      - webservice
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 5