# Stage 1: Build the Go application
FROM golang:1.25-alpine AS builder

RUN apk add --no-cache git

WORKDIR /go/src/app

# Pre-cache deps
COPY ./app .

RUN go mod download

# Stage 2: Run the application
FROM golang:1.25-alpine

RUN apk add --no-cache gcc musl-dev

WORKDIR /go/src/app

COPY --from=builder /go/src/app /go/src/app

EXPOSE 8080

CMD ["go", "run", "."]
