# Stage 1: Build the application
FROM golang:1.25-alpine AS builder

WORKDIR /go/src/app

COPY . .

RUN go mod download

# Build go app
RUN CGO_ENABLED=0 GOOS=linux go build -o /go/bin/app

# Stage 2: Run the application
# Use stage 2 to reduce the size of image also
FROM golang:1.25-alpine

WORKDIR /go/bin/app

COPY --from=builder /go/bin/app /go/bin/app

# Create a non-root user to run app
RUN adduser -D -h /home/webuser -u 1001 -s /sbin/nologin webuser

RUN chown -R webuser:webuser /go && \
    chmod -R 755 /go

USER webuser

EXPOSE 8080

CMD ["go", "run", "."]